### ISSUE TITLE
upgrade tips

### ISSUE THREAD

**Issue by liujinlong123** [patrick330602/electron-microsoft-todo#2]
Prompt when I log in:

We’ve made some changes to improve Microsoft To Do. For the best experience across all of your devices, you need to update to the latest version of To Do. Make sure your mobile and desktop To Do apps are version 2.49 or higher before October 31, 2021 to avoid any issues with cross device syncing.

Your To Do apps will no longer sync across devices, but you’ll still be able to use To Do in offline mode. After October 31, 2021, you can keep your To Do apps syncing by updating your apps to the latest version.

Don't log out because any unsynced data will be lost.

**Comment by patrick330602** [comment]
This will not effect normal uses. After dismiss for the first time it no longer showed up for me. The current web version of Microsoft ToDo is 2.55.0 do you should definitely be fine with it.
