### ISSUE TITLE
Is it normal to see the sign in page appears every singe time I open the app?

### ISSUE THREAD

**Issue by kanansnote** [patrick330602/electron-microsoft-todo#4]
So, I believe this minor [detail](https://drive.google.com/file/d/1CM72ABdzdb2sUt49yewiLSKzei_UhMpc/view?usp=share_link) should be considered, as it annoys me to deal with this every time to continue working with a to-do list. Would you mind fixing it? Thanks.

**Comment by kanansnote** [comment]
I'd like to see a response to my comment, as I noticed that the provided link had an irrelevant screenshot, which has already been corrected.

**Comment by patrick330602** [comment]
Hi,

I will try to take a look in the following days, but I am currently using neither Microsoft Todo nor snap, so it will possibly took some time fixing the issue.

**Comment by patrick330602** [comment]
Fixed, will be in next release

**Comment by kanansnote** [comment]
Thank you for fixing it.
